apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kedify
spec:
  version: "v0.0.7"
  homepage: https://github.com/kedify/kubectl-kedify
  shortDescription: "Simple TUI based shell script for installing and interfacing with Kedify."
  description: |
    It asks couple of questions and fill the answers to the proper places for K8s manifests.
  platforms:
    - selector:
        matchExpressions:
          - key: "os"
            operator: "In"
            values:
              - darwin
              - linux
      uri: https://github.com/kedify/kubectl-kedify/archive/refs/tags/v0.0.7.zip
      # 'sha256' is the sha256sum of the zip from url above (shasum -a 256 ..zip)
      sha256: 1eff93d969a8b9c6d373d0f28d0504cf9e4760d8f263f425a667a68461429d03
      # {{addURIAndSha "https://github.com/kedify/kubectl-kedify/releases/download/{{ .TagName }}/kubectl-kedify{{ .TagName }}.tar.gz" .TagName }}
      files:
        - from: "kubectl-kedify-*/kubectl-kedify"
          to: "."
        - from: "kubectl-kedify-*/preview-functions.sh"
          to: "."
        - from: "kubectl-kedify-*/insights.sh"
          to: "."
        - from: "kubectl-kedify-*/dump.sh"
          to: "."
        - from: "kubectl-kedify-*/LICENSE"
          to: "."
        - from: "kubectl-kedify-*/hso.yaml"
          to: "."
        - from: "kubectl-kedify-*/so.yaml"
          to: "."
        - from: "kubectl-kedify-*/VERSION"
          to: "."
        - from: "kubectl-kedify-*/README.md"
          to: "."
        - from: "kubectl-kedify-*/debug.sh"
          to: "."
      bin: kubectl-kedify
